<?php

namespace AppBundle\Repository;

/**
 * MissionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MissionsRepository extends \Doctrine\ORM\EntityRepository
{
}
