<?php

namespace AppBundle\Repository;

/**
 * PresidenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PresidenceRepository extends \Doctrine\ORM\EntityRepository
{
}
