app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
easy_admin_bundle:
    resource: "@EasyAdminExtensionBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin
# fos_comment_api:
#     type: rest
#     resource: "@FOSCommentBundle/Resources/config/routing.yml"
#     prefix: /api
#     defaults: { _format: html }